samsung-cnct/kraken

- cmd/container_helpers.go
at present since container names are randomly generated, and k2cli times out, it's possible for me to have two containers running a `cluster up` and a `cluster down` simultaneously; this should make those cases collide
also this makes it easier to script / grep for which container's logs to follow
> name k2 container based on deployment.cluster

- README.md
Following the instructions produces an error:
./k2cli tool kubectl --config ~/k2configs/config.yaml get pods --all-namespaces
Error: unknown flag: --all-namespaces
Terminate the options list to k2cli with the double dash (--) to avoid
parsing the options meant for kubectl.
> Terminate options list

- cmd/container_helpers.go
running container names will now be 'k2<clustername>' instead of
'k2-<clustername>' to support the generate cli subcommand under
docker 1.13
> remove trailing dash from base container name

- README.md
The AWS configuration file does function correctly when referenced as it
would be inside the docker bind mount. Documented as such.
Fixes #38
> Correct documentation regarding aws configuration file

- cmd/container_helpers.go
All the empty AWS_ environment variables were preventing boto from
trying to read the credentials file.
Associated with samsung-cnct/k2#128
> Don't create empty environment variables

- README.md
adds k2cli generate command without path explicitly defined, which will allow user to not have to specify --config /Users/<user_name>/k2configs/config.yaml when using k2cli tool"
> added note about default location of config.yaml

- cmd/container_helpers.go
this only supports one cluster in the config file at a time.  Will create a follow-on ticket for handling multiple clusters.
> Cluster name hack

- Makefile
- cmd/container_helpers.go
there are two scenarios that a cluster won't have a name:
- before a config has been genereted
- after a config has been generated but before a name has been set
we still want to access k2 functionality for these and not have k2cli
blow up.
revving version as this is an important patch and I'll cut a release
when its merged
> guard against name not exsiting and rev version

- README.md
- cmd/update.go
This PR addresses ticket #70 .
Point of interest: these changes disable k2cli's timeout of 20 minutes for the update command, since updating a node takes quite a long time, around ten minutes per node.
ToReview:
- Verify update command works as expected/necessary with k2
- Make sure the readme makes sense
> K2cliupdate

- cmd/container_helpers.go
- cmd/root.go
This adaptation brings `k2cli` up-to-speed with Docker's own command line client, to support API connections with TLS, as well as existing Unix socket and TCP host strings, configured via environment variables.
Previously the `k2cli` supported only unencrypted connections, via the Docker unix socket or a plain TCP socket. (No issue was filed in this regard.) This patch supports a wider array of configurations, all within Docker's own conventions. 
```release-note
Enable support for Docker environment variables (e.g. `DOCKER_HOST`) to configure engine API client. Command line arguments (e.g. `-d {host}`) will override OS environ.
```
> Support TLS on Docker API connections

- cmd/kubectl.go
kubectl will always be present for any major.minor version pair
so no footwork is rquired in k2cli.  just use it.
this requires samsung-cnct/k2#614
**What this PR does / why we need it**: makes `k2cli tool kubectl` work all the time
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #67 
```release-note
```
> use the scripts that exist in K2

- README.md
- cmd/generate.go
To test: run local binary of k2cli with this generate.go code, run `./k2cli generate` once to generate config file, run again and you should see an error that the config file already exists.
Fixes: https://github.com/samsung-cnct/k2cli/issues/89
> Altered generate subcommand to exit if config file already exists

- cmd/update.go
K2 supports adding/removing nodepools.  extend that to k2cli
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #110 
```adds two flags to cmd/update.go for adding/removing nodepools
```
> Nodepool flag

- cmd/helm.go
- cmd/kubectl.go
As per https://github.com/samsung-cnct/k2/issues/525, all k2 shell scripts now live in a bin folder. This is a quick fix to change filepaths to reflect this.
Completes issue #124 
Addresses K2 Issue: https://github.com/samsung-cnct/k2/issues/525 
K2 PR: https://github.com/samsung-cnct/k2/pull/718
ToReview: Check if all file paths reflect the correct location in k2
> K2 shell script calls have bin in filepath

- cmd/container_helpers.go
- cmd/container_helpers_test.go
This fix allows the user to run `export helm_override_cluster_name=true/false` when the current version of helm does not support the running version of k8s.
Fixes https://github.com/samsung-cnct/k2cli/issues/120
> Added ability check helm_override_{cluster.name} env in k2cli

- .github/ISSUE_TEMPLATE.md
- Jenkinsfile
- Makefile
- README.md
- build-scripts/fetch-credentials.sh
- cmd/cluster.go
- cmd/cluster_down.go
- cmd/cluster_helper.go
- cmd/cluster_info.go
- cmd/cluster_up.go
- cmd/cluster_update.go
- cmd/container_helpers.go
- cmd/docs.go
- cmd/generate.go
- cmd/root.go
- cmd/stages.go
- cmd/tool.go
- cmd/tool_helm.go
- cmd/tool_kubectl.go
- cmd/tool_ssh.go
- cmd/tool_ssh_update.go
- cmd/version.go
This covers issue: https://github.com/samsung-cnct/k2cli/issues/135
I changed all references to K2 and k2cli and followed the style that was already there. Used my best judgement on when to use Kraken vs Krakenlib for K2 based on the references in https://github.com/samsung-cnct/k2/pull/741, I would like feedback if there's a better approach on some of these changes.
> K2cli migration to Kraken

- cmd/cluster_down.go
- cmd/cluster_up.go
Makes subcommand --tags for up/down commands consistent with shell use, stages as a name creates confusion.
resolves https://github.com/samsung-cnct/k2cli/issues/130
```
Changes include changing stages flags found in the cluster up/down commands to tags with shorthand t, and changing root command timeout to use capital T, to avoid conflict.
```
> Changing flags: 'stages' found in up/down to 'tags',

- Makefile
we do not currently support kraken/k2cli across all of the platforms
that gox supports.  We need to only build for the platforms we support
limits build targets to our desired set
```release-note
```
> put the '\' back so that we only build the desired targets

- cmd/cluster_update.go
…lag and not as an argument, should now be consistent with all other config dependent commands.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #173 
```NONE
```
> [Issue 173] Cluster update no longer expects config to be passed as an argument.

- bin/clean/gofmt-clean.sh
- cmd/cluster_down.go
- cmd/cluster_up.go
- cmd/tool_helm.go
- cmd/tool_helm_test.go
**What this PR does / why we need it**: Fixes issues with using helm. Currently version string being pass has patch version, this is a bug addressed here. I have added tests to make sure this code works as it should, and have added an additional script to allow gfmt to do its thing.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #171 
```NONE
```
> [Issue 171] Helm: Retrieve valid version string.

- Makefile
- cmd/cluster.go
- cmd/cluster_down.go
- cmd/cluster_helper.go
- cmd/cluster_info.go
- cmd/cluster_up.go
- cmd/cluster_update.go
- cmd/tool.go
Currently we fall back to the default kraken location for a generated config file. This may be ok in this one case only but leads and can lead to confusion. I would rather have the app fail if the config file isnt defined, or if there is an issue with the one defined than falling back into some sort of default
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #184
```
No longer falling back to default config.yaml file.
```
> [Issue 184 ] Fail fast when config file isnt defined

- cmd/root.go
Suggest to change out spinner as current one gives the impression that it will terminate when reaching the end, false impression of progression. Spinning does NOT give this perception and so less likely to cause confusion.
character set 7 chosen, minor change.
see https://github.com/briandowns/spinner
```
Spinner changed to avoid impression of completion status
```
> [UI/UX] change spinner to avoid confusion about completion status

- Makefile
**What this PR does / why we need it**: On new machines without gox, compile, and releasing will fail without calling the `make deps` being called. Here we eliminate the need for this by making it part of the compile process anyway.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #28
**Special notes for your reviewer**: 
```
NONE
```
> [Issue 28] go fetching gox is now part of the compile target

- cmd/cluster_helper.go
- cmd/cluster_info.go
**What this PR does / why we need it**: Improved formatting for error message so that it is easier to read and change in the future. Fixed the message for running either `kraken tool kubectl` and `kraken tool helm` commands where `--output` flag is necessary if it is not set to the default location.
In addition ran `make verify` and had to address issues with `cluster info` style.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #21
```NONE
```
> [Issue 21] error message is now correct for the case where outputLocation is not default

- Jenkinsfile
- Makefile
set the path correctly so we are only building the kraken binaries
and not strangely named other version
add some experimental windows binaries
> release artifact cleanup/add experimental windows binaries

- README.md
This is a high level recommendation on the IAM policy necessary to run kraken. Fixes: https://github.com/samsung-cnct/kraken/issues/26
> basic guidelines for AWS IAM policy to create/run/destroy cluster

- README.md
We're mentioned as certified here: https://www.cncf.io/announcement/2017/11/13/cloud-native-computing-foundation-launches-certified-kubernetes-program-32-conformant-distributions-platforms/
Add the badges we have earned, and link to the instructions people can use to reproduce the conformance results on their own with kraken
> add certified kubernetes badges

- README.md
The default instance for etcd nodes is m4.large and not t2.small anymore as indicated [here](https://github.com/samsung-cnct/kraken-lib/blob/8129546e82d958cfa64849ca3942a7558dc5df6b/ansible/roles/kraken.config/files/config.yaml#L186)
The documentation is out of date, keeping it up to date should be a priority.
```release-note
```
> Updating Documentation to match with actual code

- .gitlab-ci.yml
- .goreleaser.yml
- Makefile
Add new build and release tasks using goreleaser: https://github.com/goreleaser/goreleaser
goreleaser builds the executables, creates TGZ and ZIP archives, generates release notes from commit messages and create the GitHub release.
It can also create a publish docker images, update homebrew definitions, create RPM, DEB, and SNAPs.
I bump version here in the Makefile in order to demonstrate the tool. We can edit that back before the merge.
See my fork for an example of this release: https://github.com/philoserf/kraken/releases/tag/1.2.4
> Add new build and release tasks

- .gitlab-ci.yml
need to update the pinned version of kraken-lib to make `kraken tools` function again.
> rev version of kraken-lib
