- cmd/down.go
- cmd/generate.go
- cmd/info.go
- cmd/tool.go
- cmd/up.go
- docs/k2cli_generate.md
- docs/k2cli_tool.md
- docs/k2cli_tool_helm.md
- docs/k2cli_tool_kubectl.md
- docs/k2cli_tool_ssh.md
- docs/k2cli_tool_ssh_update.md
we excised krakenCluster from k2, follow the convention here
> k2 no longer defaults to krakenCluster

- README.md
WORDSWORDSWORDS
make the works work well
@maratoid please give this a good read make sure I got it all correct.
> add a quick start guide and basic usage

- cmd/down.go
- cmd/generate.go
- cmd/root.go
- cmd/ssh-update.go
- cmd/up.go
- cmd/update.go
> Use spinner text fields instead of Printf

- .gitignore
- cmd/container_helpers.go
- cmd/container_helpers_test.go
@spiffxp @coffeepac @joejulian 
Added this because i stupidly did not commit my comments on the previous PR. Not meant me trying to override what had been committed, but just improvements i think will help in the long run and some patterns i think we need to establish.
updated ignore file to include .idea files. Updated container_helpers.go to use a simple function for improved readability, included a test file.
> container_helpers updated.

- README.md
- cmd/container_helpers.go
- cmd/container_helpers_test.go
- cmd/generate.go
- cmd/generate_test.go
- cmd/root.go
> added provider flag for config generation

- cmd/cluster.go
- cmd/down.go
- cmd/up.go
- cmd/update.go
depreciated configuration files (#66).
> Implement a -f option for commands which may need to tolerate

- README.md
First attempt to update readme file, open to suggestions.
> Readme to include instructions for installation view brew.

- README.md
**What this PR does / why we need it**:  README fix
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #96 
```release-note
NONE
```
> add config file explicity for consistency

- README.md
Implements changes described in #100.
> Getting Started Guide Updates

- Makefile
**What this PR does / why we need it**: update for latest k2cli release
check that this release exists on the releases tab for this repo.
```release-note
```
> next release, make it stable

- cmd/helm.go
> Created check for existence of supported version of helm

- README.md
Directions on spinning up tiny cluster for research or dev. 
Related to: https://github.com/samsung-cnct/k2/issues/621
> info on how to spinup non-HA cluster

- Makefile
update MAKEFILE with latest version number
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #133 
```release-note
```
> release version 1.0.8

- Jenkinsfile
- Makefile
- README.md
- build-scripts/golang-container/Dockerfile
- cmd/root.go
**What this PR does / why we need it**: adds release train to the k2cli jenkinsfile
```allows for Jenkins based release automation
```
> k2cli release path

- Jenkinsfile
allows release to function
```release-note
```
> forgot a pair of ampersands

- Jenkinsfile
please see https://github.com/samsung-cnct/issues/issues/46 for reasons
> gke is a noop for now

- Jenkinsfile
- Makefile
- build-scripts/golang-container/Dockerfile
**What this PR does / why we need it**: additional work, should make the release Jenkins job work
```release-note
```
> Release fix mk ii

- Jenkinsfile
- cmd/cluster.go
- cmd/cluster_down.go
- cmd/cluster_helper.go
- cmd/cluster_info.go
- cmd/cluster_up.go
- cmd/cluster_update.go
- cmd/container_helpers.go
- cmd/docs.go
- cmd/generate.go
- cmd/generate_test.go
- cmd/root.go
- cmd/stages.go
- cmd/test_helper.go
- cmd/tool.go
- cmd/tool_helm.go
- cmd/tool_kubectl.go
- cmd/tool_ssh.go
- cmd/tool_ssh_update.go
- cmd/topic.go
- cmd/version.go
**What this PR does / why we need it**: 
Several issues with k2cli have come up, including correct error management, correct use of global variables, and some cleanup of technical debt. is required.
I dont think I captured all the things for https://github.com/samsung-cnct/k2cli/issues/112
so any additional work needed can be done in this PR now, or later.
https://github.com/samsung-cnct/k2cli/issues/107
https://github.com/samsung-cnct/k2cli/issues/138
https://github.com/samsung-cnct/k2cli/issues/112
```
Fixes global flags issues
Fixes error output, panics limited to very deep level issues
```
> Changes to fix multiple problems with k2cli

- Jenkinsfile
**What this PR does / why we need it**: pushes gke to us-east1
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: k2cli resolution for samsung-cnct/issues#46
```release-note
```
> use us-east1

- Jenkinsfile
a github release wants to occur against a branch so we need to
specify it as the calculated one doesn't work in detached head state
**What this PR does / why we need it**: fixes the release jenkins job
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #<part of a series>
```release-note
```
> pass release branch parameter to makefile

- cmd/cluster.go
- cmd/cluster_down.go
- cmd/cluster_helper.go
- cmd/cluster_up.go
- cmd/cluster_update.go
- cmd/container_helpers.go
- cmd/docker_client_config.go
- cmd/generate.go
- cmd/root.go
- cmd/tool.go
- cmd/tool_helm.go
- cmd/tool_kubectl.go
- cmd/tool_ssh.go
- cmd/tool_ssh_update.go
Additional removal of panics.
Simplified how kraken commands are run, should make it fairly easy and standard now.
Changes to simplify more code.
Additional removal of panics.
Simplified how kraken commands are run, should make it fairly easy and standard now.
Changes to simplify more code.
This is preliminary work for me to write out a few more Unit Tests. It also simplifies helper code so that when we can potentially leverage future work against this code base.
``` NONE
```
> Last set of changes for easier code readability, cleanliness and fixes

- .gitignore
- README.md
fixes https://github.com/samsung-cnct/kraken/issues/160
> Updated command for fetching official build

- .github/ISSUE_TEMPLATE.md
- Godeps/Godeps.json
- Jenkinsfile
- Makefile
- README.md
- main.go
- vendor/vendor.json
Last bit of repo name cleanup
Fixes https://github.com/samsung-cnct/kraken/issues/161
> Cleanup of k2cli references/repo name

- README.md
Was [kraken-lib image] (quay.io/samsung_cnct/kraken-lib)
Should be [kraken-lib image] (quay.io/samsung_cnct/k2).
Found a couple spelling errors and fixed those as well.
> Wrong image link, fixed.

- Makefile
- bin/checks/verify-go-vet.sh
- bin/checks/verify-gofmt.sh
- bin/checks/verify-golint.sh
- bin/checks/verify-gosimple.sh
- bin/common.sh
- bin/verify.sh
Includes  all the checks we wish a developer to run. See https://github.com/samsung-cnct/k2cli/issues/155
**What this PR does / why we need it**: Creates tools to ensure quality of code, can be access with one line command `make verify` and should be used whenever changes are made.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: In part addresses https://github.com/samsung-cnct/k2cli/issues/155, does not fix it since it is only one part of the story.
**Special notes for your reviewer**: Integration with Jenkins is a possibility, but would like this vetted first.
```NONE
```
> [Make verify] added, includes the verify code and supporting code 

- README.md
**What this PR does / why we need it**:  releasing kraken should only be done via CI by a member of the kraken team via instructions that are in a private repo.  remove public release instructions from repo.
```release-note
```
> update release doc section

- README.md
**What this PR does / why we need it**: Updates documentation with current changes in code regarding updating a cluster, the expected use is to define the config file via a flag --config.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #185 
```
Documentation changed to reflect --config flag in updating a cluster.
```
> [Issue 185] cluster update --config change

- cmd/cluster_down.go
- cmd/cluster_info.go
- cmd/cluster_up.go
- cmd/cluster_update.go
- cmd/release_helper.go
- cmd/release_helper_test.go
- cmd/root.go
- cmd/tool_kubectl.go
- vendor/github.com/coreos/go-semver/LICENSE
- vendor/github.com/coreos/go-semver/semver/semver.go
- vendor/github.com/coreos/go-semver/semver/semver_test.go
- vendor/github.com/coreos/go-semver/semver/sort.go
- vendor/vendor.json
**What this PR does / why we need it**: Refactors code to the changes in line with changes in https://github.com/samsung-cnct/kraken-lib/pull/854. Allows for deterministic patters of input and correct handling of arguments passed. 
```NONE
```
> [refactor] kubectl changes to go with those submitted in kraken-lib

- bin/common.sh
- cmd/cluster_helper.go
- cmd/docker_client_config.go
- cmd/release_helper.go
- cmd/release_helper_test.go
- cmd/root.go
`make verify` did not work on the existing code base.
**Which issue this PR fixes** :
NONE
Checkout master and try `make verify`
```
...
Verifying ./bin/../bin/checks/verify-golint.sh
FAILED   ./bin/../bin/checks/verify-golint.sh	0s
...
```
checkout this PR and try `make verify` all tests pass.
other `make` tasks also continue to work as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/samsung-cnct/kraken/199)
> Fix make verify

- README.md
The bindata.go file generated by bindata is part of package main. To move it into package cmd requires a line edit.
> Update README for bindata updates

- cmd/cluster_helper.go
fixes: https://github.com/samsung-cnct/kraken/issues/214
> do not show 'cluster state' message after successful cluster down

- .gitlab-ci.yml
> remove the leading v

- .gitlab-ci.yml
**What this PR does / why we need it**:  upgrade to latest version of kraken-lib
```release-note
```
> CO-98 move release version of kraken-lib to 0.14
